### ISSUE TITLE
Rust integration

### ISSUE THREAD

**Issue by ss-o** [z-shell/z-a-rust#4]
# Rust annex improvements

Are you using this annex this rust?

**Comment by 0xMRTT** [comment]
No 😮🤣

**Comment by 0xMRTT** [comment]
I use rustup from arch repo

**Comment by ss-o** [comment]
If you would use this one we could improve the annex and add flexibility to your work. As of now there is no active rust user. To at least make suggestions.

**Comment by 0xMRTT** [comment]
I will try this. I just need to add this to my zshrc. I will use this for creating the API. But first I need to learn more about cloudfare workers and how they works

**Comment by ss-o** [comment]
Note: always treat $ZPFX as it would be the root (` / `) of system. So we can improve and simulate installation methods like in OS.

**Comment by ss-o** [comment]
It's my suggestion which should help you and the annex same time :)

**Comment by 0xMRTT** [comment]
👍👍 I will report any issues and things that can be improved
